### ISSUE TITLE
Hiya again, not an issue but general question

### ISSUE THREAD

**Issue by martsrzx91** [refulgence/quantum-fabrication#8]
Have been using your mod for a while with varying degree of success, now i am at the end of my planet journey and started to wonder how i remove the items, obviously didn't read the whole info before getting mod. Noticed the transfer speeds >_>
![image](https://github.com/user-attachments/assets/b58843da-624d-479f-b210-cc6fe0afa5d4)
![image](https://github.com/user-attachments/assets/f854de79-e928-49e7-8aec-bf069572e32e)

So my question would be is there i way i can get my stuff out of it faster? Or just imagine it is gone altogether? :D Honestly i just expected it to work the same speed both ways, because i had cranked 4 recyclers full bore with max modules at digi chest and it took the load fine.

**Comment by refulgence** [comment]
It was never intended to be used as a general multipurpose storage, that would turn it into a completely busted linked chests variation. Things you send the the Storage would only be used for the purposes of construction, that's why there is an ability to set intake limits on chests to not overfill it.

Technically in the current version (2.2.0) there is a way to manually remove things in large quantities, but you'll need to configure blueprints on a new save. Start a new game, place a ghost of a chest, then open it in a remote view and fill it with item ghosts of things you want to remove. Save blueprint. Next load your save and place that saved blueprint, the chest will get filled with items removed from the Storage.

**Comment by martsrzx91** [comment]
Sounds like a lot to get the stuff out :D I just thought perhaps i can edit something in mod so its on turbo mode. Sry to be using your mod in not its intended way, but i felt it to be similar to AE/RS mods for minecraft :)

**Comment by refulgence** [comment]
Well, if you want to edit the mod directly, you can go to scripts/constants.lua and change rates to whatever you want (Reactor_constants.item_transfer_rate for items, Reactor_constants.fluid_transfer_rate for fluids). Probably nothing would break if you multiple transfer rates by 100 and set costs to 0.

**Comment by martsrzx91** [comment]
I'm fine with the cost of doing stuff, just would like the rate out of digital storage to be faster than it is now ^^ Thanks for helping once more ;)
